language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: VytpHk+7UIhRAXK42T9xeUD2JjZRqPHVZ/SgE8jvNQr/O14BLvIrpzPyaXz4sob7SVfPpWz/YoYtEFqSWlVlFIT21mQNGebhbUuTjVgv53wrjTXGR1A99uZrMHkeOQPQnvxmbwIGQOiJSyj6jtOOK6bvH7b7WzmgUO/Sorz2rd2x+ZRUpC0eMhvhUAXtKdIpEOlOktCzxXldw/rzMUuR1W1JpU5GrejuJpnhlGacw1x9KXlCzSbroKyWgNx3K3YS41Fhlc5Twd0upclx+sOKaKl6fNPi+5ESvXlaZH7ozKWkj9X1q+e2n8iAwqOZ9DW9NGceWV8RK+WsJrtHY8zAT8C3/cZy7YqYaSbg1FMysUCEYr2iCtkysl9D4EfkGWScCN4JVgrdEi2olPVBM2gPPXyXXHDZHLVyCOVjO6kgtklLCZbM1eDMZDUR7iuBzpI6k4D9FMhyWHRvJegIz8MLoyj0R0y1zxtAGIrwzjejCHoKgZcii8AoMwDN6Ry7kPOFJrlQ9W1ZyKx39rSsXFby6+YM3YOLpqzxBWWpMPlSjXXU/VzSo8REhgsontq3OSrDV28lxAAcea6jTsbU47LtN+0AeyJbSm0n46wDHEhbWBdrOem/nQfWvABuGKXwn+5zb1yureh0dE1KOkWf732jOV57HXx50x/w9LREn0KS6cw=
