language: node_js
node_js:
- node
deploy:
  api_key:
    secure: LViCkz9xqdMXDRgqYag0RDPfiE/gcvnFtlyhW8VNXdRtp9BA3mywWaXWipIiZHqpIEX5tNnUcWtGKPzgy0LGxiQFYAqz3tb1/gBfBwZeZzIEqOyVGKdL4mza8XHgf46HAmQ0hesA9SyzLR4raKUJS+efwqEUlfbuuzQ/U2OLgFQEFxRugFWkK0eKfWYUMRXAUWJ8gmuwPOFBg6hWIhIswd8uA4n1Waw2qfWXGc/e3PEbXUOZTwEsmd+EOp3/+APEZabvwDPgA+jXDse2NT3KS25oieRqy0KhpQqdR7p7pQzddaHaIiMX3n3AkPI15MtcsHOWtVbJpwunRIsyd+I1B2OyFSQuenMWTFMtjtWQ5h6BJu7GK3BqLPNVuwTbmYZW3yeRv6aRl7sHESEbXBuWp2HIAag91FCLEaY5HzWefZu+oWYUlrjUj5P1/s/yId6UeiQ/TrOgOVsK3oc0dsXM7YLSxa1j/mynYtwk2dQmhsFzjZ/+WKYnhxBwCWxZVvldiBx+BcHkG7iQJ9ty4hegSm02nS/iJLO5hV9+3h3mOg/VxoBwGcojQf6v7UvBdhGS4PWy8WqJJPCFvNUvTSSm6dHf62ObDfmDpVUeQJqUVTbOc+ngZwEZg8eH75Z4mIgNyZdMhav7hRxSDHVru2RqNWvsyOlwXojZ2JGlZ5No7RM=
