language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: fanzw2Mo4PEV/SJHTDJF+FpdIjGdFKbKXlHFeeNH1dIciZDaNMm3ETqFLhm2M8kFpjTk/GVYIu9w6iTgoJv2y/9cM5Tk/6/UYsqLiSSvY7PauRwkzodi5ejeLx/LU0k3dXcm6ecIU4LZMLtwDrVxJelWhbbdQiWvHsZYUyXeg6KadDn35Yb7aDCCSeIu69iGuWn72AkGTzSVwsxNC0KtcIKIqT218kuKPVsMoXzFzNSFky0Ue7f03NRx4OYk0ozZpkJ+B4UToPqq1N89fl5qUJlO7GVkRyMduSNS9RelY0fgnGqmG4SzW5r3kohI/fR0kN22wKGwLTrisYng8Mx6jRu6sLc+Gp5Kz8uUerh/qLHRnLq594CzLwUTTYVjYCPBW9tuvcy6ywjUWpkv82lWM9qELzOEddjn4ha26DzMdANzuvhHRPxQb5ijQ32G1IOy0MXzOx7qmGwJ0zFPnZhEdY+038y98gTw7m2f+MV6opV0ebTNOetup6tSguOVnYEPQU4ZYzUlGeYjN6B5u9li2UyRRNSGOdgHxLEjQt8Z+peS7mGGPYkhveUc3V/8gJjXs/P+i6LJVgNMKPKjy7lFgDlmzxAuHm3wE90B1YBucY+Nh9Kp0LoNpBIMCewNbwQKJTKKfujUVPwM3HdWOOn4Vzbyu21HCQQRy6Vj1TdijEA=
